// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: events.go

export type Opcode = number /* int */;
export const OpDispatch: Opcode = 0;
export const OpHeartbeat: Opcode = 1;
export const OpIdentify: Opcode = 2;
export const OpHello: Opcode = 3;
export const OpHeartbeatAck: Opcode = 4;
export const OpResume: Opcode = 5;
export const OpInvalidSession: Opcode = 6;
export const OpVoiceState: Opcode = 7;
export const OpVoiceOffer: Opcode = 8;
export const OpVoiceAnswer: Opcode = 9;
export const OpVoiceCandidate: Opcode = 10;
export const OpVoiceResync: Opcode = 11;
export const OpVoiceScreen: Opcode = 12;
export const OpVoiceMute: Opcode = 13;
export const OpVoiceWatch: Opcode = 14;
export const OpScreenPublish: Opcode = 15;
export const OpScreenAnswer: Opcode = 16;
export const OpScreenIce: Opcode = 17;
export type EventType = string;
export const EventReady: EventType = "READY";
export const EventGuildCreate: EventType = "GUILD_CREATE";
export const EventChannelCreate: EventType = "CHANNEL_CREATE";
export const EventMessageCreate: EventType = "MESSAGE_CREATE";
export const EventMessageUpdate: EventType = "MESSAGE_UPDATE";
export const EventMessageDelete: EventType = "MESSAGE_DELETE";
export const EventTypingStart: EventType = "TYPING_START";
export const EventPresenceUpdate: EventType = "PRESENCE_UPDATE";
export const EventPermissionsUpdate: EventType = "PERMISSIONS_UPDATE";
export const EventGuildMemberAdd: EventType = "GUILD_MEMBER_ADD";
export const EventVoiceStateUpdate: EventType = "VOICE_STATE_UPDATE";
export const EventVoiceScreenUpdate: EventType = "VOICE_SCREEN_UPDATE";
export interface Frame {
  op: Opcode;
  t?: EventType;
  s?: number /* int64 */;
  d?: unknown;
}
export interface Hello {
  heartbeat_interval_ms: number /* int */;
}
export interface Identify {
  token: string;
}
export interface Resume {
  token: string;
  session_id: string;
  seq: number /* int64 */;
}
export interface User {
  id: string;
  username: string;
  avatar_key?: string;
}
export interface Guild {
  id: string;
  name: string;
  owner_id: string;
  icon_key?: string;
}
export interface Channel {
  id: string;
  guild_id: string;
  parent_id?: string;
  kind: string;
  name: string;
  topic?: string;
  position: number /* int32 */;
  last_message_id?: string;
}
export interface Member {
  guild_id: string;
  user: User;
}
export interface ChannelPermission {
  channel_id: string;
  permissions: number /* int64 */;
}
export interface GuildPermissions {
  guild_id: string;
  permissions: number /* int64 */;
  channels: ChannelPermission[];
}
export interface ReadState {
  channel_id: string;
  last_read_message_id?: string;
}
export interface Role {
  id: string;
  guild_id: string;
  name: string;
  permissions: number /* int64 */;
  position: number /* int32 */;
  is_default: boolean;
}
export interface Overwrite {
  channel_id: string;
  target_id: string;
  target_type: string;
  allow: number /* int64 */;
  deny: number /* int64 */;
}
export interface Attachment {
  id: string;
  filename: string;
  size_bytes: number /* int64 */;
  content_type: string;
  url: string;
}
export interface Message {
  id: string;
  channel_id: string;
  author: User;
  content: string;
  created_at: string;
  edited_at?: string;
  attachments: Attachment[];
}
export interface Ready {
  session_id: string;
  user: User;
  guilds: Guild[];
  channels: Channel[];
  members: Member[];
  read_states: ReadState[];
  allowed: GuildPermissions[];
  online: string[];
}
export interface MessageDelete {
  id: string;
  channel_id: string;
}
export interface TypingStart {
  channel_id: string;
  user_id: string;
  timestamp: string;
}
export interface PresenceUpdate {
  user_id: string;
  status: string;
}
export interface VoiceStateRequest {
  channel_id?: string;
  self_mute: boolean;
  self_deaf: boolean;
}
export interface SessionDescription {
  type: string;
  sdp: string;
}
export interface ICECandidate {
  candidate: string;
  sdp_mid?: string;
  sdp_mline_index?: number /* uint16 */;
  username_fragment?: string;
}
export interface VoiceStateUpdate {
  guild_id: string;
  channel_id?: string;
  user_id: string;
  self_mute: boolean;
  self_deaf: boolean;
}
export interface ScreenPublish {
  sdp: string;
}
export interface VoiceWatchRequest {
  user_id: string;
  watching: boolean;
  size: string;
}
export interface VoiceMuteRequest {
  self_mute: boolean;
}
export interface VoiceScreenRequest {
  active: boolean;
}
export interface VoiceScreenUpdate {
  guild_id: string;
  channel_id: string;
  user_id: string;
  stream_id: string;
  active: boolean;
}
